on: push
name: 🚀 Déployer via SFTP

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to AlwaysData via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ssh-qauiantiquerestaurant.alwaysdata.net
          username: qauiantiquerestaurant
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          local_path: ./
          remote_path: /www/
          sftp_only: true
          delete_remote_files: false
